name: Node.js CI
on: 
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]
env:
  TEST: test
  TEST2: test2
  USER: krzykow
  REPO: training_githubactions_start
jobs:
  build:
    env:
      TEST: test_in_job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: package docker
      run: |
        VERSION=$(date +%s)
        docker login docker.pkg.github.com --username ${{ env.USER }} --password ${{ secrets.GITHUB_TOKEN }}
        docker build . --file Dockerfile --tag docker.pkg.github.com/${{ env.USER }}/${{ env.REPO }}/app:${VERSION}
        docker push docker.pkg.github.com/${{ env.USER }}/${{ env.REPO }}/app:${VERSION}
      env:
        CI: true
        





